services:
  - type: web
    name: signlogin-app
    env: node
    buildCommand: cd .. && yarn install  # Move up to root directory
    startCommand: cd .. && yarn start   # Move up to root directory
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://new-user2:F5Id2zzDTg5MJfzX@cluster0.yv2ljqc.mongodb.net/signlogin?retryWrites=true&w=majority
    plan: free
    region: oregon
    healthCheckPath: /login
    autoDeploy: true
    disk:
      name: signlogin-data
      mountPath: /data
      sizeGB: 1